-- AWS-native synthetic banking-agent proof of concept schema.
-- Target: Amazon Aurora PostgreSQL or Amazon RDS for PostgreSQL with pgvector.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS customers (
    customer_id      BIGINT PRIMARY KEY,
    customer_name    VARCHAR(100),
    customer_segment VARCHAR(50),
    risk_class       VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS accounts (
    account_id        BIGINT PRIMARY KEY,
    customer_id       BIGINT,
    account_status    VARCHAR(30),
    available_balance NUMERIC(12,2),
    card_last4        VARCHAR(4)
);

CREATE TABLE IF NOT EXISTS transactions (
    transaction_id   BIGINT PRIMARY KEY,
    account_id       BIGINT,
    merchant         VARCHAR(100),
    amount           NUMERIC(12,2),
    transaction_time TIMESTAMPTZ,
    location         VARCHAR(100),
    status           VARCHAR(50),
    decline_code     VARCHAR(30),
    csr_reason       VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS fraud_events (
    fraud_event_id   BIGINT PRIMARY KEY,
    transaction_id  BIGINT,
    rule_code        VARCHAR(50),
    safe_description VARCHAR(500),
    fraud_score      NUMERIC,
    internal_notes   VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS policy_chunks (
    chunk_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id      VARCHAR(30),
    title          VARCHAR(200),
    chunk_text     TEXT,
    classification VARCHAR(30),
    allowed_role   VARCHAR(50),
    embedding      vector(1024)
);

CREATE TABLE IF NOT EXISTS action_requests (
    action_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id  BIGINT,
    employee_id     VARCHAR(50),
    proposed_action VARCHAR(500),
    approval_status VARCHAR(30),
    approved_by     VARCHAR(50),
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    approved_at     TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS ai_audit_log (
    audit_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_time     TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    employee_id    VARCHAR(50),
    employee_role  VARCHAR(50),
    transaction_id BIGINT,
    stage          VARCHAR(50),
    details        TEXT,
    outcome        VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_policy_role ON policy_chunks(allowed_role);
CREATE INDEX IF NOT EXISTS idx_action_status ON action_requests(approval_status);

-- For a larger policy corpus, enable an HNSW index after embeddings are loaded:
-- CREATE INDEX policy_embedding_hnsw
-- ON policy_chunks USING hnsw (embedding vector_cosine_ops);
