-- Synthetic banking-agent proof of concept schema.
-- Run as the application schema owner (for example BANKAPP).

CREATE TABLE customers (
    customer_id      NUMBER PRIMARY KEY,
    customer_name    VARCHAR2(100),
    customer_segment VARCHAR2(50),
    risk_class       VARCHAR2(30)
);

CREATE TABLE accounts (
    account_id        NUMBER PRIMARY KEY,
    customer_id       NUMBER,
    account_status    VARCHAR2(30),
    available_balance NUMBER(12,2),
    card_last4        VARCHAR2(4)
);

CREATE TABLE transactions (
    transaction_id   NUMBER PRIMARY KEY,
    account_id       NUMBER,
    merchant         VARCHAR2(100),
    amount           NUMBER(12,2),
    transaction_time TIMESTAMP,
    location         VARCHAR2(100),
    status           VARCHAR2(50),
    decline_code     VARCHAR2(30),
    csr_reason       VARCHAR2(500)
);

CREATE TABLE fraud_events (
    fraud_event_id  NUMBER PRIMARY KEY,
    transaction_id NUMBER,
    rule_code       VARCHAR2(50),
    safe_description VARCHAR2(500),
    fraud_score     NUMBER,
    internal_notes  VARCHAR2(1000)
);

CREATE TABLE policy_chunks (
    chunk_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id      VARCHAR2(30),
    title          VARCHAR2(200),
    chunk_text     CLOB,
    classification VARCHAR2(30),
    allowed_role   VARCHAR2(50),
    embedding      VECTOR(768, FLOAT32)
);

CREATE TABLE action_requests (
    action_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id  NUMBER,
    employee_id     VARCHAR2(50),
    proposed_action VARCHAR2(500),
    approval_status VARCHAR2(30),
    approved_by     VARCHAR2(50),
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP,
    approved_at     TIMESTAMP
);

CREATE TABLE ai_audit_log (
    audit_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_time     TIMESTAMP DEFAULT SYSTIMESTAMP,
    employee_id    VARCHAR2(50),
    employee_role  VARCHAR2(50),
    transaction_id NUMBER,
    stage           VARCHAR2(50),
    details         CLOB,
    outcome         VARCHAR2(50)
);
